In [169]:
import numpy as np


In [170]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [171]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)


[5 7 9]


In [172]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [173]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [174]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 * arr2
print(result)

[ 4 10 18]


In [175]:
arr = np.array([1, 2, 3, 4, 5])
mean = np.mean(arr)
print(mean)

3.0


In [176]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (2, 3))
print(reshaped_arr)

[[1 2 3]
 [4 5 6]]


In [177]:
#22222222222222222222222
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [178]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
total = np.sum(arr)
print("Total:", total)

Total: 15


In [179]:
#3333333333333333333
import numpy as np

# ساخت یک آرایه ۱ بعدی
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)

# ساخت یک ماتریس ۲ بعدی
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [180]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[0])   # دسترسی به عنصر اول
print(arr[1:4]) # دسترسی به عناصر از دوم تا چهارم

1
[2 3 4]


In [181]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr.shape)  # ابعاد آرایه را نمایش می‌دهد
print(arr.size)   # تعداد کل عناصر آرایه را نمایش می‌دهد

(3, 2)
6


In [182]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result_add = arr1 + arr2
print(result_add)

# مثال دیگر: تقسیم عناصر دو آرایه
result_divide = arr2 / arr1
print(result_divide)

[5 7 9]
[4.  2.5 2. ]


In [183]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

# مثال دیگر: تغییر شکل آرایه به شکل سه بعدی
reshaped_arr_3d = arr.reshape(1, 2, 3)
print(reshaped_arr_3d)

[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]]


In [184]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])
sum_row = np.sum(arr, axis=1)    # جمع اعداد در هر سطر
mean_col = np.mean(arr, axis=0)  # میانگین اعداد در هر ستون

print(sum_row)
print(mean_col)

[ 3  7 11]
[3. 4.]


In [185]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6]])
filtered_arr = arr[arr % 2 == 0]
print(filtered_arr)

# مثال دیگر: انتخاب عناصر کوچکتر از میانگین آرایه
below_mean = arr[arr < np.mean(arr)]
print(below_mean)

[2 4 6]
[1 2 3]


In [186]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result_inner = np.inner(arr1, arr2)   # ضرب داخلی دو آرایه
print(result_inner)

# مثال دیگر: تابع لگاریتم بر روی آرایه
log_arr = np.log(arr1)
print(log_arr)

32
[0.         0.69314718 1.09861229]


In [187]:
import numpy as np

arr = np.array([1, 2, 3, 4])
exp_arr = np.exp(arr)   # محاسبه تابع نمایی بر روی همه عناصر
print(exp_arr)

# مثال دیگر: محاسبه سینوس همه عناصر آرایه
sin_arr = np.sin(arr)
print(sin_arr)

[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [188]:
###7777777777777777777777
import numpy as np
arr = np.array([6 , 220 , 9 , 1 , 22 , 34])
print(arr)

[  6 220   9   1  22  34]


In [189]:
arr1 = np.array([6 , 220 , 9 , 1 , 22 , 34])
arr2 = np.array([87 , 120 , 69 , 13 , 10 , 4])
result = arr1 + arr2
print(result)

[ 93 340  78  14  32  38]


In [190]:
arr = np.array([[6 , 220 , 9 , 1 , 22 , 34], [87 , 120 , 69 , 13 , 10 , 4]])
print(arr.shape)

(2, 6)


In [191]:
arr = np.array([[6 , 220 , 9 , 1 , 22 , 34], [87 , 120 , 69 , 13 , 10 , 4]])
print(arr)

[[  6 220   9   1  22  34]
 [ 87 120  69  13  10   4]]


In [192]:
arr1 = np.array([6 , 220 , 9 , 1 , 22 , 34])
arr2 = np.array([87 , 120 , 69 , 13 , 10 , 4])
result = arr1 * arr2
print(result)

[  522 26400   621    13   220   136]


In [193]:
#####888888888888888888888
arr = np.array([6 , 220 , 9 , 1 , 22 , 34])
mean = np.mean(arr)
print(mean)


48.666666666666664


In [194]:
arr = np.array([6 , 220 , 9 , 1 , 22 , 34])
reshaped_arr = np.reshape(arr, (2, 3))
print(reshaped_arr)

[[  6 220   9]
 [  1  22  34]]


In [195]:
import numpy as np

arr = np.array([6 , 220 , 9 , 1 , 22 , 34])
print(arr)


[  6 220   9   1  22  34]


In [196]:
import numpy as np
arr = np.array([6 , 220 , 9 , 1 , 22 , 34])
total = np.sum(arr)
print("Total:", total)


Total: 292


In [197]:
import numpy as np
arr1d = np.array([6 , 220 , 9 , 1 , 22 , 34])
print(arr1d)

[  6 220   9   1  22  34]


In [198]:
arr2d = np.array([[6 , 220 , 9 , 1 , 22 , 34], [64 , 20 , 91 , 13 , 42 , 54], [16 , 90 , 465 , 100 , 92 , 134]])
print(arr2d)

[[  6 220   9   1  22  34]
 [ 64  20  91  13  42  54]
 [ 16  90 465 100  92 134]]


In [199]:
import numpy as np

arr = np.array([6 , 220 , 9 , 1 , 22 , 34])
print(arr[0])   # دسترسی به عنصر اول
print(arr[1:4]) # دسترسی به عناصر از دوم تا چهارم

6
[220   9   1]


In [200]:
import numpy as np

arr = np.array([[6 , 220 , 9 , 1 , 22 , 34], [64 , 20 , 91 , 13 , 42 , 54], [16 , 90 , 465 , 100 , 92 , 134]])
print(arr.shape)  # ابعاد آرایه را نمایش می‌دهد
print(arr.size)   # تعداد کل عناصر آرایه را نمایش می‌دهد

(3, 6)
18


In [201]:
import numpy as np

arr1 = np.array([6 , 220 , 9 , 1 , 22 , 34])
arr2 = np.array([64 , 20 , 91 , 13 , 42 , 54])
result_add = arr1 + arr2
print(result_add)


[ 70 240 100  14  64  88]


In [202]:
result_divide = arr2 / arr1
print(result_divide)

[10.66666667  0.09090909 10.11111111 13.          1.90909091  1.58823529]


In [203]:
import numpy as np

arr = np.array([64 , 20 , 91 , 13 , 42 , 54])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)

[[64 20 91]
 [13 42 54]]


In [204]:
reshaped_arr_3d = arr.reshape(60, 46, 142)
print(reshaped_arr_3d)

ValueError: cannot reshape array of size 6 into shape (60,46,142)

In [ ]:
import numpy as np

arr = np.array([[6 , 220 , 9 , 1 , 22 , 34], [64 , 20 , 91 , 13 , 42 , 54], [16 , 90 , 465 , 100 , 92 , 134]])
sum_row = np.sum(arr, axis=1)    # جمع اعداد در هر سطر
mean_col = np.mean(arr, axis=0)  # میانگین اعداد در هر ستون

print(sum_row)
print(mean_col)

[ 3  7 11]
[3. 4.]


In [ ]:
import numpy as np

arr = np.array([[6 , 220 , 9 , 1 , 22 , 34], [64 , 20 , 91 , 13 , 42 , 54], [16 , 90 , 465 , 100 , 92 , 134]])
filtered_arr = arr[arr % 2 == 0]
print(filtered_arr)

[  6 220  22  34  64  20  42  54  16  90 100  92 134]


In [ ]:
####9999999999999999999999
below_mean = arr[arr < np.mean(arr)]
print(below_mean)

[ 6  9  1 22 34 64 20 13 42 54 16]


In [ ]:
import numpy as np

arr1 = np.array([6 , 220 , 9 , 1 , 22 , 34])
arr2 = np.array([64 , 20 , 91 , 13 , 42 , 54])
result_inner = np.inner(arr1, arr2)   # ضرب داخلی دو آرایه
print(result_inner)

8376


In [ ]:
# مثال دیگر: تابع لگاریتم بر روی آرایه
log_arr = np.log(arr1)
print(log_arr)

[1.79175947 5.39362755 2.19722458 0.         3.09104245 3.52636052]


In [ ]:
import numpy as np

arr = np.array([6 , 220 , 9 , 1 , 22 , 34])
exp_arr = np.exp(arr)   # محاسبه تابع نمایی بر روی همه عناصر
print(exp_arr)

[4.03428793e+02 3.50579098e+95 8.10308393e+03 2.71828183e+00
 3.58491285e+09 5.83461743e+14]


In [ ]:
# مثال دیگر: محاسبه سینوس همه عناصر آرایه
sin_arr = np.sin(arr)
print(sin_arr)


[-0.2794155   0.08839871  0.41211849  0.84147098 -0.00885131  0.52908269]
